FROM maven:3.9-eclipse-temurin-25 AS build

WORKDIR /src
COPY . .
RUN mvn -B -pl apps/jui-app-customer -am package -DskipTests

FROM eclipse-temurin:25

WORKDIR /app
COPY --from=build /src/apps/jui-app-customer/target/jui-app-customer-0.0.1-SNAPSHOT.jar /app/app.jar

CMD ["java", "-jar", "/app/app.jar"]
