<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.jui</groupId>
  <artifactId>jui-all</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  
  <packaging>pom</packaging>
  
  <properties>
    
    <timestamp>${maven.build.timestamp}</timestamp>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    
    <!-- maven -->
    <maven.build.timestamp.format>yyyy-MM-dd HH:mmss Z</maven.build.timestamp.format>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <maven-jar-plugin.version>3.1.1</maven-jar-plugin.version>
    
    <!-- sonar -->
    <sonar.scanner.force-deprecated-java-version>true</sonar.scanner.force-deprecated-java-version>
    <sonar.java.coveragePlugin>jacoco</sonar.java.coveragePlugin>
    <sonar.dynamicAnalysis>reuseReports</sonar.dynamicAnalysis>
    <sonar.language>java</sonar.language>
    <sonar.coverage.jacoco.xmlReportPaths>${basedir}/lm-report/target/site/jacoco-aggregate/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>

    <jui.version>0.0.1-SNAPSHOT</jui.version>
    <jetty.version>11.0.20</jetty.version>
    <gson.version>2.10.1</gson.version>
    

  </properties>
  
  <modules>
    
    <module>jui-core</module>
    
    <!--
    <module>jui-toolkits</module>
    <module>jui-playground</module>
    <module>jui-apps/jui-apps-dashboard</module>
    <module>jui-sandbox-wasm</module>
    -->
    
  </modules>
  
  <dependencyManagement>
    
    <dependencies>
      
      <dependency>
        <groupId>com.jui</groupId>
        <artifactId>jui-core</artifactId>
        <version>${jui.version}</version>
      </dependency>
      
      <dependency>
        <groupId>com.jui</groupId>
        <artifactId>jui-toolkits</artifactId>
        <version>${jui.version}</version>
      </dependency>

    <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-server</artifactId>
        <version>${jetty.version}</version>
    </dependency>
    <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-servlet</artifactId>
        <version>${jetty.version}</version>
    </dependency>
    <dependency>
        <groupId>com.google.code.gson</groupId>
        <artifactId>gson</artifactId>
        <version>${gson.version}</version>
    </dependency>

    <dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
      <version>1.18.42</version>
		</dependency>
	
		<!-- https://mvnrepository.com/artifact/org.bouncycastle/bcpkix-jdk15to18 -->
		<dependency>
		    <groupId>org.bouncycastle</groupId>
		    <artifactId>bcpkix-jdk18on</artifactId>
		    <version>1.80</version>
		</dependency>

		<dependency>
        	<groupId>org.apache.commons</groupId>
        	<artifactId>commons-csv</artifactId>
        	<version>1.9.0</version>
    	</dependency>

		<!-- H2 Database JDBC Driver -->
    <dependency>
        <groupId>com.h2database</groupId>
        <artifactId>h2</artifactId>
        <version>2.2.224</version>
    </dependency>
        
        <!-- MySQL JDBC Driver 
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.33</version>
			<scope>test</scope>
        </dependency>
        -->
        
        <!-- MariaDB JDBC Driver 
        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>3.1.1</version>
        </dependency>
        -->

        <!-- PostgreSQL JDBC Driver 
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.5.4</version>
			<scope>test</scope>            
        </dependency>
        -->

        <!-- Oracle JDBC Driver 
        <dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc8</artifactId>
            <version>19.8.0.0</version>
			<scope>test</scope>           
        </dependency>
        -->

        <!-- Microsoft SQL Server JDBC Driver 
        <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
            <version>10.2.1.jre8</version>
			<scope>test</scope>            
        </dependency>
        -->

        <!-- SQLite JDBC Driver 
        <dependency>
            <groupId>org.xerial</groupId>
            <artifactId>sqlite-jdbc</artifactId>
            <version>3.42.0.0</version>
        </dependency>
        -->

    <dependency>
      <groupId>org.duckdb</groupId>
      <artifactId>duckdb_jdbc</artifactId>
      <version>1.1.0</version>
		</dependency>

		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
      <version>5.10.0</version>
		</dependency>
      
    </dependencies>
    
  </dependencyManagement>
  
  <repositories>
    
    <repository>
      <id>github</id>
      <url>https://maven.pkg.github.com/mwzero/jui</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      
      <snapshots>
        <enabled>true</enabled>
      
      </snapshots>
      
    </repository>
    
  </repositories>
  
  <distributionManagement>
    
    <snapshotRepository>
      
      <id>github</id>
      
      <url>https://maven.pkg.github.com/mwzero/jui</url>
      
    </snapshotRepository>
    
    <repository>
      
      <id>github</id>
      
      <url>https://maven.pkg.github.com/mwzero/jui</url>
      
    </repository>
    
  </distributionManagement>
  
  <build>
    
    <pluginManagement>
      
      <plugins>
        
        <plugin>
          
          <groupId>org.apache.maven.plugins</groupId>
          
          <artifactId>maven-surefire-plugin</artifactId>
          
          <version>2.22.2</version>
        
        </plugin>
        
        <plugin>
          
          <groupId>org.apache.maven.plugins</groupId>
          
          <artifactId>maven-compiler-plugin</artifactId>
          
          <version>3.8.1</version>
          
          <configuration>
            
            <source>${maven.compiler.source}</source>
            
            <target>${maven.compiler.target}</target>
          
          </configuration>
        
        </plugin>
      
      </plugins>
    
    </pluginManagement>
    
    <plugins>
      
      <!--
      <plugin>
        <groupId>org.sonarsource.scanner.maven</groupId>
        <artifactId>sonar-maven-plugin</artifactId>
        <version>3.9.1.2184</version>
        <executions>
          <execution>
            <id>default-sonar</id>
            <phase>verify</phase>
            <goals>
              <goal>sonar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.8.8</version>
        <configuration>
          <append>true</append>
          <skip>false</skip>
        </configuration>
        <executions>
          <execution>
            <id>prepare-agent</id>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
          <execution>
            <id>report</id>
            <goals>
              <goal>report-aggregate</goal>
            </goals>
          </execution>
          <execution>
            <id>merge-results</id>
            <phase>verify</phase>
            <goals>
              <goal>merge</goal>
            </goals>
            <configuration>
              <fileSets>
                <fileSet>
                  <directory>${code.coverage.project.folder}</directory>
                  <includes>
                    <include>**/target/jacoco.exec</include>
                  </includes>
                </fileSet>
              </fileSets>
              <destFile>${code.coverage.overall.data.folder}/jacoco.exec</destFile>
            </configuration>
          </execution>
        </executions>
      </plugin>
      
      -->
      
      <plugin>
        
        <artifactId>maven-surefire-plugin</artifactId>
        
        <configuration>
          
          <forkCount>1</forkCount>
          
          <reuseForks>true</reuseForks>
          
          <!--
          <skipTests>false</skipTests>
          -->
        
        </configuration>
        
        <dependencies>
          
          <dependency>
            
            <groupId>org.ow2.asm</groupId>
            
            <artifactId>asm</artifactId>
            
            <version>6.2</version>
          
          </dependency>
        
        </dependencies>
      
      </plugin>
      
    </plugins>
    
  
  </build>
  
  <profiles>
    
    <!--
    <profile>
      <id>sonar</id>
      <activation>
        <activeByDefault>false</activeByDefault>
      </activation>
      <properties>
        <sonar.host.url>
          http://34.154.228.85:7090/
        </sonar.host.url>
        <sonar.projectKey>
          LM
        </sonar.projectKey>
        <sonar.login>
          sqp_8a66e7b668485fb59ee94e307c9bc97057c1444a
        </sonar.login>
      </properties>
    </profile>
    -->
    
  </profiles>
  
</project>
