package com.jui.model;

import com.google.gson.Gson;

import lombok.Getter;
import lombok.Setter;

/**
 * The content that the back-end sends to the front-end for insertion into the HTML page. 
 * It encapsulates all components generated by the server, such as text, images, or structured data, 
 * that are rendered as part of the page.
 * 
 */
@Getter
@Setter
public class JuiContent {
	
	 String sidebar;
     String main;
     
     public String toJsonString() {
	     Gson gson = new Gson();
	     return gson.toJson(this);
     }

}
