# This workflow will build a docker image using Docket and then publish it to ghcr.io registry

name: Publich Dashboard App Docker over ghcr.io

on:
  workflow_dispatch:
      inputs:
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options:
          - info
          - warning
          - debug
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps: 
      - uses: actions/checkout@v3
      - name: Build and push the image
        run : |
          docker login --username mwzero --password ${{ github.token }} ghcr.io
          docker build ./jui-apps/jui-apps-dashboard --tag ghcr.io/mwzero/jui-apps-dashboard:latest
          docker push ghcr.io/mwzero/jui-app-dashboard:latest
